sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123qwe
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com

#    access-key-id: Alibaba Cloud AccessKey ID （敏感信息）
#    access-key-secret: AccessKey Secret（敏感信息）
    bucket-name: coolice2001
  redis:
    host: 192.168.138.130
    port: 6379
    password: 123qwe
    database: 10